/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_tkgktyk_wearablepad_NativeMethod */

#ifndef _Included_jp_tkgktyk_wearablepad_NativeMethod
#define _Included_jp_tkgktyk_wearablepad_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_tkgktyk_wearablepad_NativeMethod
 * Method:    getInputEventHeaderSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_tkgktyk_wearablepad_NativeMethod_getInputEventHeaderSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
